### ISSUE TITLE
Feedback on Assignment

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/intro-R-Python-syedaslamsheikdawood#1]
Hi Aslam,

Great work on the assignment. Some minor feedback:
1. It's important to have authorship on all notebooks (first name, last name)
2. I would like to see some markdown formatting for the title and section headers (use "#" Title, and "##" Section titles). 

These changes make the notebook more readable and shareable. 

I am giving you full credit, contingent on you fixing these minor issues by September 15th. 
-Greg

**Comment by Syedaslamsheikdawood** [comment]
Done the changes as per issues raised
